### ISSUE TITLE
 Split code

### ISSUE THREAD

**Issue by crisszkutnik** [GuidoDipietro/TP-ASDR#1]
For god's sake split the code between different files. It's impossible to read it in its actual state. Please.

@GuidoDipietro I'm almost certain it is your fault.

**Comment by GuidoDipietro** [comment]
Dear crisszk,
I will give an explanation as to why this code is unreadable.

To quote my Professor:

> "Bueno, les mostré todo el TP. Copienló y péguenló total ya lo hice."

That, followed by a Word file containing the code you just read, and cringed, was what we got as he explained the Recursive Descent Syntactical Analyzer.

Yeah. Mhm. That's right. A Word document.  

With the `.docx` extension.

Let me clarify that once again in case it wasn't clear enough:

He used **Word** as a code editor. A few screen captures of that holy grail of wisdom:

![image](https://user-images.githubusercontent.com/48221146/97055242-cae34a80-155c-11eb-95e0-fa7c950b5b2f.png)

Nevermind - one capture will do. Sorry for the 🤮.

So, getting back on track: they asked us to hand in this assignment, but - good lord! - they hadn't ever notified us about such a task prior to today's email.  
So, what should we have done? "Vamos a pedir el TP de ASDR." Write all this code from scratch? I think it's a better idea to just hit the keys Ctrl, C, and V in the right order (plus some clicks here and there) to get all the code from the beautifully formatted Word document into a `.c` file, and boom, this repository was born.

Therefore, yes, the unreadability of the code is certainly my fault, for it was my decision to take the code **exactly** as it was and paste it into a `.c` file, but you can't blame my _Professor_ for not knowing about code editors!

Edit your code in Word. Forget about modularity. All in one file, no File Systems needed whatsoever. Let's code like in the future.

**Comment by GuidoDipietro** [comment]
Yo, @crisszkutnik, check what I've done

https://github.com/GuidoDipietro/TP-ASDR/tree/master/ASDR
